version: "3.9"
services:
  sw_etl:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/src
    image: sw-etl
    entrypoint: ["./main.py"]
    working_dir: /src
